# Generated by Django 4.2.4 on 2023-08-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityclasses',
            old_name='Instructor_name',
            new_name='instructor_name',
        ),
    ]
