# Generated by Django 4.2.4 on 2023-08-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='intial_deposit',
            new_name='initial_deposit',
        ),
    ]
